include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_pub_dependencies: false
    prefer_const_literals_to_create_immutables: false
