include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true

linter:
  rules:
    sort_pub_dependencies: false
    prefer_const_literals_to_create_immutables: false
