# CAUTION : DO NOT USE PUBSPEC ASSIST. ADD DEPENDENCIES MANUALLY. DONT BE LAZY. PUBSPEC ASSIST WILL
# OVERWRITE THE DEPENDENCIES AND DELETE THE COMMENTS AND YOU WILL HAVE TO ORGANIZE IT AGAIN AND
# IT WILL BE A PAIN.

name: storayge
description: todo - add desc.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # Navigation
  auto_route: ^3.0.4

  # Firebase Suite
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  google_sign_in: ^5.2.1

  # Functional Programming
  fpdart: ^0.0.12

  # Value Equality
  equatable: ^2.0.3
  freezed_annotation:

  # Business Logic and Dependency Injection
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  hydrated_bloc: ^8.0.0
  get_it: ^7.2.0

  # Local Storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # Data and Internet
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.3.0

  # Render
  flutter_svg: ^1.0.0
  flutter_screenutil: ^5.0.3
  simple_animations: ^4.0.1
  bottom_nav_layout: ^3.0.9
  google_nav_bar: ^5.0.5
  boxy: ^2.0.5

  # Misc
  lint: ^1.8.1
  logger: ^1.1.0
  path_provider: ^2.0.8
  supercharged: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.1.4
  auto_route_generator: ^3.0.1
  json_serializable: ^6.0.1
  freezed: ^0.15.0+1

  # Mocking and Testing
  mocktail: ^0.2.0
  bloc_test: ^9.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/character_unboxing.svg
    - assets/images/svg/storayge_logo.svg
    - assets/images/svg/storayge_icon.svg
    - assets/images/trash.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Montserrat_Alt
      fonts:
        - asset: assets/fonts/MontserratAlternates-Semibold.ttf
          weight: 600
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700

    - family: StoraygeIcons
      fonts:
        - asset: assets/fonts/StoraygeIcons.ttf
